- README.md
Added DUnitX, DUnit, DUnit2, DelphiSpec, Delphi-Mocks, DUnit-XML
> Added Unit Testing Category and several libraries in that area.  

- README.md
A good project to include is Delphi-ORM: Object-Relational Mapping for Delphi XE7, XE6, XE5, XE4, XE3 and XE2 (Win32). Supports for FirebirdSQL, SQLServer and SQLite3.
> Add Delphi-ORM

- README.md
Sorry for single pull request for multiple items.
> Some links from my collection

- README.md
Descriptions taken from http://www.libtml.org/docs/libtml-pascal/.
The TML Library is released under the terms of the Lesser General Public license (LGPL).
> Added TML Messaging Suite to Communications

- .travis.yml
- README.md
Hi,
Some links are broken and could be validated automatically.
See issue #15
> Validate URLs

- README.md
URL http://regexpstudio.com/TRegExpr/TRegExpr.html return 404 erro.
Change to https://github.com/ashumkin/RegExpr
> Error 404 http://regexpstudio.com/TRegExpr/TRegExpr.html

- README.md
There is more information on their repo's readme and they included a few examples.
> Adds LeakCheck to the list

- README.md
JsonDataObjects
Marshmallow ORM for Delphi
DSharp
delphi-leakcheck
slf4p
Daraja HTTP Framework
> Some good code libs

- README.md
> Added GpProfiler2017 tool

- README.md
Google Map alternative source
delphiXERO - Delphi API for XERO
Delphi Library Helper - IDE Library Path Editor
Mobile Image Creator - Creating Icons and Launcher Images for Delphi Mobile Applications (Firemonkey).
> Google Map alternative source and couple of tools

- README.md
QuickLib
QuickORM
QuickImageFX
> Added new libraries

- README.md
Hi,
I added a library I wrote a while ago that is a port of FuzzyWuzzy.
> Added FuzzyWuzzy.pas - FPC port of FuzzyWuzzy

- README.md
Boss is a dependency manager for delphi projects
> Added Boss

- README.md
Add QuickJS Engine to scripting section.
> Update README.md - Add QuickJS Engine to scripting section

- README.md
Added Zint-Barcode-Generator-for-Delphi
> Added Zint-Barcode-Generator-for-Delphi

- README.md
Adding machine learning  to this list.
> Machine learning addition

- README.md
Adds a specific seeded hashing algorithm that seems to be missing with most crypto suites.
> Add MurMur-Delphi

- README.md
Open source template engine for Delphi. Tested on XE4 and XE8+.
> Add Sempare Template Engine reference

- README.md
Pretty little known library with great features
> Add cool Image32 lib

- README.md
> added new lib

- README.md
Added this one: [https://github.com/MHumm/delphi-code-coverage-wizard-plus](https://github.com/MHumm/delphi-code-coverage-wizard-plus)
> Added Delphi Code Coverage Wizard Plus

- README.md
This neural network library contains state-of-the-art neural network algorithms with highly optimized implementations.
> Added CAI Neural API
